version: '3'

services:
  portal-nginx:
    build: ./docker/nginx
    ports:
      - "8010:443"
    depends_on:
      - portal-php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/ssl/certs

  portal-php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
