version: '3'

services:
  portal-nginx:
    build: ./docker/nginx
    ports:
      - "8010:443"
    depends_on:
      - portal-php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/ssl/certs

  portal-php:
    build: ./docker/php
    volumes:
      - .:/var/www/html

  portal-redis:
    build: ./docker/redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data

  redis-webui:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_NAME=local
      - REDIS_1_HOST=portal-redis
      - REDIS_1_PORT=6379
    ports:
      - "8081:80"
    depends_on:
      - portal-redis
